on:
  pull_request:
  push:
env:
  RUST_BACKTRACE: "1"
name: "ci"
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Run Clippy
        run: nix develop .#clippy --command cargo clippy --all-targets --all-features
      - name: Sccache stats
        run: nix develop .#clippy --command sccache --show-stats
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop .#fmt --command cargo fmt --check
  with-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build
        run: nix build
      # TODO: get `sccache` enabled here.
  loom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build everything
        run: nix develop --command cargo build --all-targets
      - name: Run tests
        run: nix develop --command cargo test --all-targets
      - name: Run loom tests
        run: nix develop --command ./loom.sh -- loom
      - name: Sccache stats
        run: nix develop .#clippy --command sccache --show-stats
  with-cargo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: [stable, beta, 1.72.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version}}
      - run: cargo build --all-targets
      - run: cargo test
