on:
  pull_request:
  push:
jobs:
  clippy:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: auguwu/clippy-action@1.2.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - run: nix-shell --pure --run "cargo fmt --check"
  with-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Build
        run: |
          nix build
  with-cargo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: [stable, beta, 1.72.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version}}
      - run: cargo build --all-targets
      - run: cargo test
      - run: ./loom.sh -- loom

